A = [1 2; 3 4]
transposeA = transpose(A)
inverseA = inv(A)
eigen = eig(A)
expA = expm(A)
B = [1 2 3 4]
C = [5 6 7 8]
D = dot(B, C)
normB = norm(B)
normC = norm(C)
detA = det(A)
rankA = rank(A)
traceA = trace(A)
nullA = null(A)
E = [1 2 3; 4 5 6; 7 8 9]
detE = det(E)
rankE = rank(E)
traceE = trace(E)
nullE = null(E)